sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
language: node_js
node_js:
   - "10.19.0"
script:
  - yarn run test
notifications:
  slack:
    secure: WjAMfg4XM4r3ppsTOxzYNhuWUkBujlQjNm0wQee7jbvVAbCOcim1yqoK5Oc8emuHUVqcB7fr59kd7nf4tOqwlDbW0hWwswsDdUG61uRxj6OL8X6BYI0cmlL2GALNqAnbM/+bI7PieXYXV0fsK+0BlcYwzUcVTgKl30Ey9gCONX4=
