common:
  iframe_message: "get_analytics_session"
  get_param_name: "analytics_session"
  single_beacon: false

cookies:
  first_party_enabled: true
  version: 1
  yogurt:
    name: "yogurt_session"
  analytics:
    name: "analytics_session"
    duration: 604800 # 1 week

api:
  settings:
    key: "settings"
    set_account: "setAccount"
    set_callback: "setCallback"
    redirect_to: "redirectTo"
  yogurt:
    key: "yogurt"
    product_click: "productClick"
  site:
    key: "site"
    send_pageview: "sendPageview"
  ecommerce:
    key: "ecommerce"
    add_item: "addItem"
    add_transaction: "addTransaction"

url:
  analytics_session:
    create: "/track/create?yogurt_session=#{yogurt_session}"
    connect: "/track/connect"
  beacon: "/track/actions/create?analytics_session=#{analytics_session}"
  utils:
    third_party_step1: "/track/check/third_party/step_1.js"
    third_party_step2: "/track/check/third_party/step_2.js"

params:
  analytics_session: "analytics_session"
  signature: 'sig'
  url: 'url'
  shop_code: 'shop_code'
  actions: 'actions'
