common:
  iframe_message: "get_analytics_session"
  get_param_name: "analytics_session"
  single_beacon: false
xdomain_session_timeout: 5000
auto_pageview_timeout: 1000
send_auto_pageview: true
cookies:
  first_party_enabled: true
  version: 1
  analytics:
    name: "__sa_session"
    duration: 1800 # 30 minutes

api:
  settings:
    key: "settings"
    yogurt_session: "setYogurtSession"
    yogurt_user: "setYogurtUser"
    set_account: "setAccount"
    set_callback: "setCallback"
    redirect_to: "redirectTo"
  yogurt:
    key: "yogurt"
    product_click: "productClick"
  site:
    key: "site"
    send_pageview: "sendPageView"
  ecommerce:
    key: "ecommerce"
    add_item: "addItem"
    add_transaction: "addTransaction"

url:
  analytics_session:
    create: "/track/create?yogurt_session=#{yogurt_session}&yogurt_user_id=#{yogurt_user_id}&shop_code=#{shop_code}&flavor=#{flavor}&metadata=#{metadata}"
    connect: "/track/connect?shop_code=#{shop_code}"
  beacon: "/track/actions/create?analytics_session=#{analytics_session}"
  utils:
    third_party_step1: "/track/check/third_party/step_1.js"
    third_party_step2: "/track/check/third_party/step_2.js"

params:
  analytics_session: "analytics_session"
  signature: 'sig'
  url: 'url'
  referrer: 'referer' # Misspelling of referrer, check https://en.wikipedia.org/wiki/HTTP_referer
  shop_code: 'shop_code'
  actions: 'actions'
