name: CI

on:
  # manual trigger for every branch
  workflow_dispatch:
  # push on master and PR merge on master
  push:
    branches: [ master ]
  # PRs (first and subsequent pushes)
  pull_request:

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout analytics.js
        uses: actions/checkout@v2
        with:
          path: analytics.js
      # ===== run tests =====
      - name: Run tests
        working-directory: ./analytics.js
        run: docker-compose run --entrypoint docker/entrypoint-ci.sh builder
      # ===== cleanup =====
      - name: Clean analytics.js containers
        working-directory: ./analytics.js
        run: docker-compose down -v
        if: ${{ always() }}
      # ===== slack report =====
      - name: slack success-message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Roufianos
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: Tests successful
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: ref,actions url
        if: ${{ success() }}
      - name: slack fail-message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Roufianos
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: Tests failed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: ref,actions url
        if: ${{ failure() }}
      - name: slack cancel-message
        uses: rtCamp/action-slack-notify@v2
        if: ${{ cancelled() }}
        env:
          SLACK_USERNAME: Roufianos
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: Tests cancelled
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: ref,actions url
